spring:
  datasource:
    url: jdbc:postgresql://localhost:5467/queueless
    username: queueless
    password: queueless
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration

server:
  port: 8090

logging:
  level:
    root: INFO
    pe.edu.utec.queueless: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE

queueless:
  pago:
    gateway: mock
  storage:
    impl: local
  firebase:
    enabled: false
